## House Price Prediction using Linear Regression

Refer to this link for column description: https://www.kaggle.com/competitions/neolen-house-price-prediction/data

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

Read csv here. Change your file path.

In [3]:
df = pd.read_csv("data.csv")

Print no. of rows & columns in the dataset

In [4]:
df.shape

(1259, 81)

View 5 row from the top

In [5]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

View 5 rows from the bottom/end

In [6]:
df.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1254,1255,60,RL,60.0,6931,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2008,WD,Normal,165400
1255,1256,50,RM,52.0,6240,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,127500
1256,1257,20,RL,91.0,14303,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2008,WD,Normal,301500
1257,1258,30,RL,56.0,4060,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,99900
1258,1259,80,RL,59.0,9587,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2008,WD,Normal,190000


Feature column are the predictor or independent variables. It is represented as X; or $x_1, x_2, .... x_n$

Target column are the response or dependent variables. They depend upon independent or predictor variables $x_1, x_2, .., x_n$. 

In $y = wx + b$, $y$ is the response/target/independent variable and $x$ is the feature/predictor/independent variable.

### Specify the feature and target columns here.

In [10]:
#df.columns.tolist() 
#listing all the columns 
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='str')

In [11]:
feature_column = ['LotArea', 'TotalBsmtSF', 'PoolArea']
target_column  = 'SalePrice'

In [12]:
print(f"Feature Columns: {feature_column}")
print(f"Target Column: {target_column}")

Feature Columns: ['LotArea', 'TotalBsmtSF', 'PoolArea']
Target Column: SalePrice

Show feature columns

In [26]:
df[feature_column]

      LotArea  TotalBsmtSF  PoolArea
0        8450          856         0
1        9600         1262         0
2       11250          920         0
3        9550          756         0
4       14260         1145         0
...       ...          ...       ...
1254     6931          746         0
1255     6240          884         0
1256    14303         1986         0
1257     4060          864         0
1258     9587          856         0

[1259 rows x 3 columns]

Show target column.

In [13]:
df[target_column]

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1254    165400
1255    127500
1256    301500
1257     99900
1258    190000
Name: SalePrice, Length: 1259, dtype: int64

### Split the dataset into train set and test set.

`train_test_split()` accepts `test_size` parameter that specify the test set proportion. `.2` means `20%` of the total data is split as test set.

`random_state` parameters helps to create re-producible train and test split. On each invocation of `train_test_split()` with `random_state=42` creates the same train and test split. See more here: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

In [30]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size=.2, random_state=42)

In [31]:
print(f"Train Shape: {train.shape}")
print(f"Test Shape: {test.shape}")

Train Shape: (1007, 81)
Test Shape: (252, 81)

Separate out the feature and target column in train and test set.

In [32]:
train_x = train[feature_column]
train_y = train[target_column]

test_x = test[feature_column]
test_y = test[target_column]

In [35]:
## TODO : Write code here to to print train_x, train_y, test_x, test_y
## See how the columns are different in feature and target dataframes

In [33]:
print("===== TRAIN_X =====")
print(train_x.head())

print("\n===== TRAIN_Y =====")
print(train_y.head())

print("\n===== TEST_X =====")
print(test_x.head())

print("\n===== TEST_Y =====")
print(test_y.head())

===== TRAIN_X =====
     LotArea  TotalBsmtSF  PoolArea
243    10762          626         0
514    10594          768         0
966     9600          728         0
199     9591         1713         0
270    10728         1095         0

===== TRAIN_Y =====
243    120000
514     96500
966    160000
199    274900
270    266000
Name: SalePrice, dtype: int64

===== TEST_X =====
      LotArea  TotalBsmtSF  PoolArea
76       8475          952         0
1026     9300         1268         0
43       9200          938         0
666     18450         1021         0
529     32668         2035         0

===== TEST_Y =====
76      135750
1026    167500
43      130250
666     129000
529     200624
Name: SalePrice, dtype: int64

Print shape of each dataframe here

In [22]:
print("train_x shape:", train_x.shape)
print("train_y shape:", train_y.shape)

print("test_x shape:", test_x.shape)
print("test_y shape:", test_y.shape)

train_x shape: (1007, 3)
train_y shape: (1007,)
test_x shape: (252, 3)
test_y shape: (252,)

In [23]:
print("train_x columns:")
print(train_x.columns)

print("\ntrain_y name:")
print(train_y.name)

train_x columns:
Index(['LotArea', 'TotalBsmtSF', 'PoolArea'], dtype='str')

train_y name:
SalePrice

In [35]:
test_x

      LotArea  TotalBsmtSF  PoolArea
76       8475          952         0
1026     9300         1268         0
43       9200          938         0
666     18450         1021         0
529     32668         2035         0
...       ...          ...       ...
430      1680          483         0
32      11049         1234         0
156      7200            0         0
376      8846          870         0
620      8248          864         0

[252 rows x 3 columns]

In [20]:
test_y

76      135750
1026    167500
43      130250
666     129000
529     200624
         ...
430      85400
32      179900
156     109500
376     148000
620      67000
Name: SalePrice, Length: 252, dtype: int64

## Linear Regression model 

Import LinearRegression model

In [24]:
from sklearn.linear_model import LinearRegression


model = LinearRegression()

Call `.fit()` method to learn the model parameters. 

In $y = wx + b$, `w` and `b` are the model parameters. `.fit()` computes these parameters.

In [25]:
model.fit(train_x, train_y)

LinearRegression()

Print learned `w` here.

See how no. of values change on changing the no. of feature columns.

In [26]:
model.coef_

array([  0.83413391, 117.0724966 , 166.20381694])

Print bias/intercept `b` here.

In [27]:
model.intercept_

np.float64(48695.29254816295)

Use the learned linear regression model to predict on the test data set.

In [28]:
y_pred = model.predict(test_x)

In [29]:
print(y_pred)

[167217.59416974 204900.6635675  166183.32629996 183616.0821571
 314187.30959549 143125.04927389 157257.20937112 153780.7358913
 160981.61726582 146114.17509716 124720.62982971 250009.41752006
 274026.71583965 170406.74866598 177350.56151715 199502.87489033
 168681.64052135 304319.62470081 159697.62748836 231474.7457767
 231383.3319115  183265.06706225 234454.62689218 266098.85767775
 137527.76124811 151672.15353948 209535.27789465 197267.57341946
 168432.55035264 159789.59279778 184990.29155664 153782.58155897
 178818.40449393 236237.40375093 187375.7150109  137657.52315317
 172658.38089049 114466.15056164 119181.41530794 235888.27856349
 152127.89546224 223747.42061705 151133.9237146  225257.06164385
 172308.63214879 264669.76178027 195759.28191577 139077.77050709
 161532.6167939  166207.45800838 128769.35522474 153173.0652477
 149431.4453505  180512.44728906 118098.52103688 157392.37511906
 134125.18769667 128389.22286268 163595.90109536 192916.55311982
 173974.07063163 154520.41602229 206075.79477773 190137.07516261
 150652.57027538 206998.99255298 178806.83190906 156906.19140105
 225180.13286462 285452.74314766 141689.44664508 181756.14094438
 152285.31938064 213220.82236028 166957.39150571 247070.32867128
 162794.1902457  242964.59129618 258616.6265419  232482.40165621
 176756.74134534 201226.58883118 174210.90361111 169318.66113168
 183427.22990477 239538.02738115 216525.67483492 253231.04506379
 163285.41482217 212995.39562574 210970.77523362 148146.59644405
 283119.17734048  55647.79866291 140030.49564893 193192.3441992
 148422.22361779 140763.1339738  201002.038036   257176.58161381
 189955.85752514 187287.28575683 165809.58431946 114848.05360613
 199587.15846995 161968.57507764 127267.38199259 127727.19217028
 153912.78961842 138708.24918629 222477.63323587 162047.75962392
 167484.51701998 123668.44610844 231568.75627352 195648.2007613
 155181.68181559 103777.28417253 143979.43796938 183420.06356418
 162241.63061484 208625.04934233 181718.54674368 132294.21665588
 261924.55498234 122846.06218618 164577.9704535  320334.21444645
 134096.71079407 277996.25093795 166667.24031577 124260.19897299
 157256.563697    53366.44242729 146070.29580472 150148.80051051
 193300.75948725 304307.04345739 161784.91321333 196129.67055027
 252823.31704798 177521.79454282 134813.48951478  89653.04137984
 102925.40893869 149951.1910693  298105.10257894 196221.20364045
 141831.65950865 147629.937751   312174.17330879 125411.50615957
 247656.26759357  99601.84253367 171314.01472703 157614.21868331
 164461.89843074 274378.8838131  132897.48393043 180131.64713301
 140639.55187065 134914.36154264 214600.66830223 142295.8730554
  59290.46143472 131775.76228532 113608.22581079 175426.35593857
 145593.37072965 188038.18079776 161502.58797325 128769.35522474
 151446.23066038 207186.87220178 159182.41542353 165854.43090593
 161110.82772665 132607.54619536 171916.5892125  105128.58110185
 225646.63823343 143295.71692019 163628.24385794 169323.10055575
 204774.77858235 173977.42928712 188891.3363199  189608.39485507
 221536.39750894 219658.67072963 255753.65445831 102646.43129417
 195507.11290604 280989.6555958  136284.9017267  186824.88182274
 178756.9002244  179792.98876677 160115.82232538 123694.65905927
 304473.83949327 321478.55193694 157420.66356187  55822.13264947
 218167.44988359 197450.68383956 177482.43784442 178145.26949092
 173300.60582399 220282.50866217 137693.88418052 135886.96167819
 199601.26663634 158714.99275084 169958.02886375 210032.82074266
 171504.30254765 151672.15353948 198177.7769767  154695.59520269
 211929.71335718 166337.93482237 158068.82166261 175184.18547579
 158604.3356309  157292.27905022 235133.62007718 190244.45392181
 156229.3318829  120740.51974515 141446.28964362 141885.16042846
 190509.33445987 134094.46608695 231566.74714114 258069.44575885
  75763.69741951 167087.12841569 200082.77535555 243167.96756471
 113904.11883297 249215.16963584 201192.48932133 156540.9710347
 159822.29036008 143196.69056    173668.30647219 106642.65336801
 202379.09888654  54701.05667847 157927.11312832 156725.86607236]

Import `root_mean_squared_error` from `sklearn.metrics` and calculate the RMSE for the predictions.

https://scikit-learn.org/stable/modules/generated/sklearn.metrics.root_mean_squared_error.html

In [39]:
print(df['SalePrice'].mean())

181144.81254964258

In [38]:
# write your code here
from sklearn.metrics import mean_squared_error, root_mean_squared_error


MSE = mean_squared_error(test_y, y_pred)
print(f"Mean Squared Error: {MSE}")

# calculate RMSE
RMSE = np.sqrt(mean_squared_error(test_y, y_pred))
print(f"Root Mean Squared Error: {RMSE}")

Mean Squared Error: 3553596882.7309093
Root Mean Squared Error: 59612.05316654434

In [40]:
rmse_percent = RMSE / df['SalePrice'].mean() * 100
print(f"RMSE % of average price: {rmse_percent:.2f}%")

RMSE % of average price: 32.91%

In [45]:
print('------------------------------------------------------THINGS THAT I LEARNT:----------------------------------------------------------')
print('The RMSE is around 33 % which is high. ' )
print('By changing and adding more features, I will try decreasing the RMSE score in next notebook. ')

------------------------------------------------------THINGS THAT I LEARNT:----------------------------------------------------------
The RMSE is around 33 % which is high.
By changing and adding more features, I will try decreasing the RMSE score in next notebook.

Assignement: Add/remove features from `feature_column` and run all the code to see how `MSE` and `RMSE` changes. Document the RMSE and MSE and corresponding features.