## House Price Prediction using Linear Regression

Refer to this link for column description: https://www.kaggle.com/competitions/neolen-house-price-prediction/data

In [95]:
# This Python 3 environment comes with many helpful analytics libraries installed

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

Read csv here. Change your file path.

In [96]:
df = pd.read_csv("data.csv")

Print no. of rows & columns in the dataset

In [97]:
df.shape

(1259, 81)

View 5 row from the top

In [98]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

View 5 rows from the bottom/end

In [99]:
df.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1254,1255,60,RL,60.0,6931,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,2Story,7,5,2003,2004,Gable,CompShg,VinylSd,VinylSd,Stone,92.0,Gd,TA,PConc,Gd,TA,No,Unf,0,Unf,0,746,746,GasA,Ex,Y,SBrkr,760,896,0,1656,0,0,2,1,3,1,Gd,7,Typ,1,Gd,BuiltIn,2003.0,Fin,2,397,TA,TA,Y,178,128,0,0,0,0,NaN,NaN,NaN,0,7,2008,WD,Normal,165400
1255,1256,50,RM,52.0,6240,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,BrkSide,Norm,Norm,1Fam,1.5Fin,6,6,1931,1950,Gable,CompShg,Wd Sdng,Wd Sdng,NaN,0.0,TA,TA,BrkTil,TA,Fa,No,LwQ,425,Unf,0,459,884,GasA,TA,Y,FuseA,959,408,0,1367,0,0,1,0,3,1,TA,6,Typ,1,Gd,Detchd,1978.0,Unf,1,560,TA,TA,Y,0,0,0,0,120,0,NaN,NaN,NaN,0,11,2007,WD,Normal,127500
1256,1257,20,RL,91.0,14303,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NoRidge,Norm,Norm,1Fam,1Story,8,5,1994,1994,Hip,CompShg,HdBoard,HdBoard,BrkFace,554.0,Gd,TA,PConc,Gd,TA,Gd,GLQ,1314,Unf,0,672,1986,GasA,Ex,Y,SBrkr,1987,0,0,1987,1,0,2,0,2,1,Gd,7,Typ,1,TA,Attchd,1994.0,Fin,2,691,TA,TA,Y,262,36,0,0,0,0,NaN,NaN,NaN,0,8,2008,WD,Normal,301500
1257,1258,30,RL,56.0,4060,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,Edwards,Feedr,Norm,1Fam,1Story,5,8,1922,1950,Gable,CompShg,Wd Sdng,Wd Sdng,NaN,0.0,TA,TA,PConc,Fa,TA,No,Unf,0,Unf,0,864,864,GasA,Ex,Y,SBrkr,864,0,0,864,0,0,1,0,2,1,TA,4,Typ,0,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,96,0,0,0,0,NaN,NaN,NaN,0,7,2009,WD,Normal,99900
1258,1259,80,RL,59.0,9587,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,SLvl,7,5,2005,2005,Gable,CompShg,VinylSd,VinylSd,Stone,182.0,Gd,TA,PConc,Gd,TA,Gd,GLQ,655,Unf,0,201,856,GasA,Ex,Y,SBrkr,1166,0,0,1166,1,0,2,0,2,1,Gd,5,Typ,0,NaN,Attchd,2005.0,Fin,2,400,TA,TA,Y,212,0,0,0,0,0,NaN,NaN,NaN,0,7,2008,WD,Normal,190000


Feature column are the predictor or independent variables. It is represented as X; or $x_1, x_2, .... x_n$

Target column are the response or dependent variables. They depend upon independent or predictor variables $x_1, x_2, .., x_n$. 

In $y = wx + b$, $y$ is the response/target/independent variable and $x$ is the feature/predictor/independent variable.

### Specify the feature and target columns here.

In [100]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      218
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [101]:
#df.columns.tolist() 
#listing all the columns 
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='str')

In [102]:
# numeric_df = df.select_dtypes(include='number')

# numeric_df.loc[:, numeric_df.isna().sum() == 0]

In [ ]:
# #FYI : using these features show around 20% error
# feature_column = ['LotArea', 'TotalBsmtSF', 'PoolArea', 'OverallQual', 'GarageCars', 'YearBuilt','MoSold']
# target_column  = 'SalePrice'

In [ ]:
# FYI : using these features show aroud 19% error
feature_column = ['LotArea', 'TotalBsmtSF', 'PoolArea', 'OverallQual', 'OverallCond','YearBuilt', 'BsmtFinSF1','BsmtUnfSF','TotalBsmtSF','FullBath','HalfBath','OpenPorchSF','GarageCars','GarageArea','YrSold','YearBuilt','MoSold']
target_column  = 'SalePrice'

In [104]:
#'OverallQual', 'GarageCars', 'YearBuilt','MoSold'

In [105]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      218
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [106]:
print(f"Feature Columns: {feature_column}")
print(f"Target Column: {target_column}")

Feature Columns: ['LotArea', 'TotalBsmtSF', 'PoolArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'BsmtFinSF1', 'BsmtUnfSF', 'TotalBsmtSF', 'FullBath', 'HalfBath', 'OpenPorchSF', 'GarageCars', 'GarageArea', 'YrSold', 'YearBuilt', 'MoSold']
Target Column: SalePrice

Show feature columns

In [107]:
df[feature_column]

,LotArea,TotalBsmtSF,PoolArea,OverallQual,OverallCond,YearBuilt,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,FullBath,HalfBath,OpenPorchSF,GarageCars,GarageArea,YrSold,YearBuilt,MoSold
0,8450,856,0,7,5,2003,706,150,856,2,1,61,2,548,2008,2003,2
1,9600,1262,0,6,8,1976,978,284,1262,2,0,0,2,460,2007,1976,5
2,11250,920,0,7,5,2001,486,434,920,2,1,42,2,608,2008,2001,9
3,9550,756,0,7,5,1915,216,540,756,1,0,35,3,642,2006,1915,2
4,14260,1145,0,8,5,2000,655,490,1145,2,1,84,3,836,2008,2000,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,6931,746,0,7,5,2003,0,746,746,2,1,128,2,397,2008,2003,7
1255,6240,884,0,6,6,1931,425,459,884,1,0,0,1,560,2007,1931,11
1256,14303,1986,0,8,5,1994,1314,672,1986,2,0,36,2,691,2008,1994,8
1257,4060,864,0,5,8,1922,0,864,864,1,0,96,0,0,2009,1922,7
1258,9587,856,0,7,5,2005,655,201,856,2,0,0,2,400,2008,2005,7

Show target column.

In [108]:
df[target_column]

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1254    165400
1255    127500
1256    301500
1257     99900
1258    190000
Name: SalePrice, Length: 1259, dtype: int64

### Split the dataset into train set and test set.

`train_test_split()` accepts `test_size` parameter that specify the test set proportion. `.2` means `20%` of the total data is split as test set.

`random_state` parameters helps to create re-producible train and test split. On each invocation of `train_test_split()` with `random_state=42` creates the same train and test split. See more here: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

In [109]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size=.2, random_state=42)

In [110]:
print(f"Train Shape: {train.shape}")
print(f"Test Shape: {test.shape}")

Train Shape: (1007, 81)
Test Shape: (252, 81)

Separate out the feature and target column in train and test set.

In [111]:
train_x = train[feature_column]
train_y = train[target_column]

test_x = test[feature_column]
test_y = test[target_column]

In [112]:
## TODO : Write code here to to print train_x, train_y, test_x, test_y
## See how the columns are different in feature and target dataframes

In [113]:
print("===== TRAIN_X =====")
print(train_x.head())

print("\n===== TRAIN_Y =====")
print(train_y.head())

print("\n===== TEST_X =====")
print(test_x.head())

print("\n===== TEST_Y =====")
print(test_y.head())

===== TRAIN_X =====
     LotArea  TotalBsmtSF  PoolArea  OverallQual  OverallCond  YearBuilt  \
243    10762          626         0            6            6       1980
514    10594          768         0            5            5       1926
966     9600          728         0            5            7       1940
199     9591         1713         0            8            5       2004
270    10728         1095         0            8            5       2006

     BsmtFinSF1  BsmtUnfSF  TotalBsmtSF  FullBath  HalfBath  OpenPorchSF  \
243           0        626          626         1         1           28
514           0        768          768         1         0            0
966         428        300          728         1         1           70
199        1088        625         1713         2         0           26
270           0       1095         1095         2         1           51

     GarageCars  GarageArea  YrSold  YearBuilt  MoSold
243           1         288    2009       1980       4
514           1         200    2007       1926       6
966           1         256    2009       1940       6
199           3         856    2009       2004       1
270           3        1053    2006       2006       8

===== TRAIN_Y =====
243    120000
514     96500
966    160000
199    274900
270    266000
Name: SalePrice, dtype: int64

===== TEST_X =====
      LotArea  TotalBsmtSF  PoolArea  OverallQual  OverallCond  YearBuilt  \
76       8475          952         0            4            7       1956
1026     9300         1268         0            5            5       1960
43       9200          938         0            5            6       1975
666     18450         1021         0            6            5       1965
529     32668         2035         0            6            3       1957

      BsmtFinSF1  BsmtUnfSF  TotalBsmtSF  FullBath  HalfBath  OpenPorchSF  \
76           228        724          952         1         0            0
1026         697        571         1268         1         0            0
43           280        167          938         1         0            0
666          187        111         1021         2         1          265
529         1219        816         2035         3         0            0

      GarageCars  GarageArea  YrSold  YearBuilt  MoSold
76             1         283    2008       1956       4
1026           2         461    2010       1960       4
43             1         308    2008       1975       7
666            2         596    2007       1965       8
529            2         484    2007       1957       3

===== TEST_Y =====
76      135750
1026    167500
43      130250
666     129000
529     200624
Name: SalePrice, dtype: int64

Print shape of each dataframe here

In [114]:
print("train_x shape:", train_x.shape)
print("train_y shape:", train_y.shape)

print("test_x shape:", test_x.shape)
print("test_y shape:", test_y.shape)

train_x shape: (1007, 17)
train_y shape: (1007,)
test_x shape: (252, 17)
test_y shape: (252,)

In [115]:
print("train_x columns:")
print(train_x.columns)

print("\ntrain_y name:")
print(train_y.name)

train_x columns:
Index(['LotArea', 'TotalBsmtSF', 'PoolArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'BsmtFinSF1', 'BsmtUnfSF', 'TotalBsmtSF', 'FullBath',
       'HalfBath', 'OpenPorchSF', 'GarageCars', 'GarageArea', 'YrSold',
       'YearBuilt', 'MoSold'],
      dtype='str')

train_y name:
SalePrice

In [116]:
test_x

,LotArea,TotalBsmtSF,PoolArea,OverallQual,OverallCond,YearBuilt,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,FullBath,HalfBath,OpenPorchSF,GarageCars,GarageArea,YrSold,YearBuilt,MoSold
76,8475,952,0,4,7,1956,228,724,952,1,0,0,1,283,2008,1956,4
1026,9300,1268,0,5,5,1960,697,571,1268,1,0,0,2,461,2010,1960,4
43,9200,938,0,5,6,1975,280,167,938,1,0,0,1,308,2008,1975,7
666,18450,1021,0,6,5,1965,187,111,1021,2,1,265,2,596,2007,1965,8
529,32668,2035,0,6,3,1957,1219,816,2035,3,0,0,2,484,2007,1957,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,1680,483,0,6,5,1971,387,96,483,1,1,0,1,264,2008,1971,7
32,11049,1234,0,8,5,2007,0,1234,1234,2,0,30,2,484,2008,2007,1
156,7200,0,0,5,7,1950,0,0,0,1,0,0,2,625,2006,1950,6
376,8846,870,0,5,5,1996,298,572,870,1,0,0,2,576,2006,1996,7
620,8248,864,0,3,3,1914,41,823,864,1,0,0,0,0,2008,1914,9

In [117]:
test_y

76      135750
1026    167500
43      130250
666     129000
529     200624
         ...
430      85400
32      179900
156     109500
376     148000
620      67000
Name: SalePrice, Length: 252, dtype: int64

## Linear Regression model 

Import LinearRegression model

In [118]:
from sklearn.linear_model import LinearRegression


model = LinearRegression()

Call `.fit()` method to learn the model parameters. 

In $y = wx + b$, `w` and `b` are the model parameters. `.fit()` computes these parameters.

In [119]:
model.fit(train_x, train_y)

LinearRegression()

Print learned `w` here.

See how no. of values change on changing the no. of feature columns.

In [120]:
model.coef_

array([ 7.09721686e-01,  2.08473029e+01,  1.07729456e+02,  2.48110589e+04,
        3.98835397e+03, -4.86351663e+00,  2.36914080e+01, -6.98971942e+00,
        2.08473029e+01,  2.53916538e+04,  2.15136449e+04,  1.91549972e+01,
        3.79359198e+03,  4.76125658e+01, -1.35608473e+03, -4.86351663e+00,
       -6.25845414e+02])

Print bias/intercept `b` here.

In [121]:
model.intercept_

np.float64(2617298.033268162)

Use the learned linear regression model to predict on the test data set.

In [122]:
y_pred = model.predict(test_x)

In [123]:
print(y_pred)

[ 88622.00084468 140915.61614552 113628.72068642 212980.02030287
 273570.61719744 172991.49058048 121759.26547891 227427.80255278
 134800.09386529 233752.83374345 176721.63415085 299455.58211764
 271040.2586819  178041.49012951 185569.0673947  201536.88334012
  87101.55098679 392985.51175931 105013.74716545 232636.14015298
 206936.85753066 173386.46580449 237094.28589471 131118.94568216
  68664.18697379 145689.51486571 139797.49885275 208925.19930089
 119224.4419183   96682.60236966 137896.3798327  224924.57643743
 104559.49839134 265213.28787501 312745.22427073 167492.84731605
 141233.01445894  79074.99856711  94721.86241641 253446.65894932
 136436.58235431 225460.62274468 225368.82077306 207412.42795483
 144570.52314986 108898.48409606 220500.86855386 141519.78363616
 150074.56125859 219610.96700414 115544.14723207 106717.01207715
 136209.98274208 150172.33403069  60591.79448332 146760.80984649
 153985.00053613  97937.53476035 178743.74115751 216370.81081088
 151817.43923412  94750.12529225 203998.11168121 254213.20335136
 209860.01702207 154128.44628879 109506.27595659 198038.60747121
 337506.88818366 338293.72340866 102045.48717935 128785.817814
 222467.70837505 265741.65059351 137471.79646366 233479.70158379
 117114.4079441  266710.23931013 267461.67909147 295229.8549228
 113135.31520674 175199.65481786 185772.03399754 129526.98860807
 148982.43213311 279070.26921526 205234.04131203 203188.52420418
 211132.02530539 196082.67746957 285906.05024892 206559.30221958
 351806.34009981  51475.89711173 189655.24981845 227175.15430905
 106623.95481877 212853.544633   218993.43059289 294772.61161406
 120840.10010024 140559.76597414  87294.50053325  58728.12575531
 132915.33585424 254571.58254554 211511.77807032 161062.87517763
 203389.12452858 172200.39454019 184738.17878844  86394.54555123
 220366.81326535  94079.25057734 218104.85139864 183053.05057974
 208426.50597809  98587.29548289 211262.23972741 172454.48204898
 112076.1102176  195845.52121896 162775.89062577 164426.39588475
 174429.8259265  180329.90772737 119213.65346568 300256.8657244
  91985.8913445  206116.7083034  135233.70441465 218020.63863705
 121937.74457725  42357.39701808  93926.29848394 124479.48932876
 221093.97674023 349427.26810165 201713.73919024 252991.60980973
 220927.80421852 135734.0821022   51402.90979952   9007.50090225
 225469.33673193 219222.43370068 291810.71889149 151895.83463674
 134355.03520405 239670.14426532 320255.03196432 196753.19154502
 208645.26012169 110707.37131173 247896.41507314 209332.50890735
 245094.13085937 225177.82869041 156407.23884715 179123.62109782
 192875.22024139 109553.39480094 244537.05256512 184903.58794754
  65467.5221     117729.00688425  98581.70240337 163014.83355981
 101426.16587305 253530.65435008 137889.9096445  149510.84939433
 218907.31556659 196164.88935039  75521.040688   106048.69093952
 157727.76539652 104763.81779617 118154.09331526  45292.10039071
 187532.18422986 152332.24915956 183384.2737452  210792.87463993
 364793.33073154  82852.23371433 243554.5711983  194644.43085362
 205970.75601339 161921.99695083 255182.36369621 186764.12346724
 244571.31224549 326764.88680895 120659.73863493  89719.92273534
 283877.50700453 137219.19444078 201486.35010553  49162.03900781
 425121.38756945 289258.93592904 160947.41132898  48770.83119699
 153533.78806746 253212.76652188 124432.96635998 147446.73938888
 159053.9253372  183260.03103644 127300.9853922  119620.22367248
 182587.09955882 214336.00911207 216601.55211366 205837.38636874
 155948.48313865 149042.37607841 197497.4168107  202073.19178994
 256691.42652697 217712.40661534 110408.63456803 227447.42991983
  65161.3762566   72518.68334469 162253.19354542 121123.2272419
 112739.74812489 207381.09775629 196406.40734238 241515.82422302
 261925.46581559 113719.41031572 250904.29690123 260825.26063103
  75790.34495821 227606.83375781 192526.66775003 245606.68342005
 113813.79609576 301912.45677697 274882.94297004  57185.72237974
 109270.40664758  94429.76218282 174860.41377124 132632.12366851
 225219.31190254  94089.74592659 123211.16238083  18916.37865867]

Import `root_mean_squared_error` from `sklearn.metrics` and calculate the RMSE for the predictions.

https://scikit-learn.org/stable/modules/generated/sklearn.metrics.root_mean_squared_error.html

In [124]:
print(df['SalePrice'].mean())

181144.81254964258

In [125]:
# write your code here
from sklearn.metrics import mean_squared_error, root_mean_squared_error


MSE = mean_squared_error(test_y, y_pred)
print(f"Mean Squared Error: {MSE}")

# calculate RMSE
RMSE = np.sqrt(mean_squared_error(test_y, y_pred))
print(f"Root Mean Squared Error: {RMSE}")

Mean Squared Error: 1234713633.333731
Root Mean Squared Error: 35138.49218924641

In [127]:
rmse_percent = RMSE / df['SalePrice'].mean() * 100
print(f"RMSE % of average price: {rmse_percent:.2f}%")

RMSE % of average price: 19.40%

RMSE is around 19% , which is lesser than the previous one i.e 33%. This shows that this model is better